version: "3.8"
services:
  s0711citybot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
